using Solid.Identity.Protocols.Saml2p.Options;
using Solid.Identity.Protocols.Saml2p.Models.Protocol;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Text;
using Solid.Identity.Protocols.Saml2p.Abstractions;

namespace Solid.Identity.Protocols.Saml2p.Models.Context
{
    /// <summary>
    /// A context class used with <see cref="Saml2pIdentityProviderEvents.OnCompleteSso"/>.
    /// </summary>
    public class CompleteSsoContext
    {
        /// <summary>
        /// The partner id.
        /// </summary>
        public string PartnerId { get; internal set; }

        /// <summary>
        /// The Saml2p SP partner.
        /// </summary>
        public ISaml2pServiceProvider Partner { get; internal set; }

        /// <summary>
        /// The original <see cref="AuthnRequest"/>.
        /// <para>If the flow being completed is IDP initiated, then this was generated by the IDP and cached.</para>
        /// </summary>
        public AuthnRequest Request { get; internal set; }

        /// <summary>
        /// The <see cref="SamlResponse"/> to be sent to the SP.
        /// </summary>
        public SamlResponse Response { get; internal set; }
    }
}
