name: build_branch
on:
  push:
    branches-ignore:
      - master
    #paths:
    #  - ".workflows/**/*.*" 
    #  - "src/**/*.*"
  workflow_dispatch:
    inputs:
      incremented-version:
        description: 'The part of the version number to increment.'
        required: true
        default: 'patch'
      
env:
  incremented-version: patch
jobs:
  build_branch:
    name: build_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Semver tags
        id: semver
        uses: SOLIDSoftworks/semver-tags@1.0.2
        with:
          # The github token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          incremented-value: ${{ env.incremented-version }}   
          dry-run: true

      #- name: setup_dotnet
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 3.1.200      
      #- name: set_dotnet_roll_forward
      #  uses: allenevans/set-env@v1.0.0
      #  with:
      #    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: '2'
      #    
      #- name: install_dependencies
      #  run: dotnet restore ./src/Solid.Identity.Protocols.Saml2p.sln
      #- name: build
      #  run: dotnet build ./src/Solid.Identity.Protocols.Saml2p.sln --configuration Release --no-restore -p:VersionPrefix=${{ env.version }}
      #- name: test
      #  run: dotnet test ./src/Solid.Identity.Protocols.Saml2p.sln --configuration Release --no-restore --no-build
